### ISSUE TITLE
Please implement file queue

### ISSUE THREAD

**Issue by atolstoy** [kareigu/Real-ESRGAN-ncnn-vulkan-UI#1]
Hi and take my regards for your great work! That's the upscaling GUI I've been looking for for a long time!
It works just fine, but it would be great if [Real-ESRGAN-ncnn-vulkan-UI](https://github.com/kareigu/Real-ESRGAN-ncnn-vulkan-UI) could process several files in a queue. I guess that implies adding some sort of a filelist Qt6 widget and few code lines.

Thanks in advance anyway!

**Comment by kareigu** [comment]
Hi and thanks!

I agree that a queue system would be great to have and should be relatively simple to add as well. 

Key question becomes how to make it ergonomic to use, because I still want the UI to be fast and simple for single files.
One thought that came to mind was possibly having a third button next to `Start` for adding something to the queue with the current settings. Then a separate button could appear to allow access to a queue window or something equivalent to manage your queue.

Currently working on the CLI downloading functionality whenever I get around to doing stuff but will definitely keep this on my mind for once I'm done with that.

Cheers for the suggestion

**Comment by atolstoy** [comment]
Sounds promising. Keep up the good work!
Meanwhile [this](https://github.com/cmdrkotori/qtwaifu2x) Waifu2x front-end is quite well-designed imo. Maybe you can borrow some concept from it.

**Comment by kareigu** [comment]
Hello!

Took a while but this is now included as the latest release [v0.4.0](https://github.com/kareigu/Real-ESRGAN-ncnn-vulkan-UI/releases/tag/v0.4.0)

This is just a really crude implementation, but it works.

Thanks again for the suggestion.
